export type District =
  | 'Xuhui'
  | "Jing'an"
  | 'Huangpu'
  | 'Changning'
  | 'Putuo'
  | 'Hongkou'
  | 'Pudong'
  | 'Yangpu'
  | 'Minhang'

/**
 * The drawing that gets stamped on the map. Each archetype has its own
 * hand-inked marker, so the map reads as a picture before it reads as data.
 */
export type Archetype =
  | 'standing-bar'
  | 'lane-house'
  | 'roastery'
  | 'garden'
  | 'laboratory'
  | 'gallery'
  | 'riverside'
  | 'neighborhood'
  | 'bakery'
  | 'hidden-door'

export type Tag =
  | 'laptop-welcome'
  | 'no-laptops'
  | 'outdoor'
  | 'plane-trees'
  | 'standing-only'
  | 'own-roast'
  | 'single-origin'
  | 'pastry'
  | 'view'
  | 'late'
  | 'early'
  | 'dog-friendly'
  | 'english-spoken'
  | 'cash-free'
  | 'books'
  | 'natural-wine'
  | 'matcha'
  | 'step-free'

/**
 * Every axis runs 0..100. These are the dials the Vibe Compass moves, and the
 * distance between a reader's dials and a cafe's axes is the whole ranking.
 */
export interface Axes {
  /** 0 = pure conversation room, 100 = deep-work sanctuary */
  focus: number
  /** 0 = hushed, 100 = buzzing */
  energy: number
  /** 0 = grab and go, 100 = settle in for hours */
  linger: number
  /** 0 = flawless classics, 100 = fermented-mango-espresso-tonic */
  adventure: number
  /** 0 = under Y20 a cup, 100 = Y90 tasting flight */
  spend: number
}

export interface Cafe {
  id: string
  name: string
  nameZh: string
  district: District
  /** The street-level scene it belongs to. Shanghai coffee is a street sport. */
  hood: string
  street: string
  streetZh: string
  lat: number
  lng: number
  archetype: Archetype
  axes: Axes
  tags: Tag[]
  signature: string
  /** One sentence of field note. Editorial, subjective, on purpose. */
  note: string
  /** Local open/close in decimal hours, e.g. 7.5 = 07:30 */
  opens: number
  closes: number
  seats: number
  price: 1 | 2 | 3
  /** Per-axis provenance and structured signals. Absent = pure editorial. */
  evidence?: Evidence
  /** How the record entered the atlas. Absent = curated ('editorial'). */
  source?: 'editorial' | 'imported'
}

/** Where an axis value comes from, in increasing order of authority. */
export type AxisSource = 'editorial' | 'measured' | 'observed' | 'voted'

export interface AxisEvidence {
  /** Blended 0..100 value actually used by the compass. */
  value: number
  /** 0..1 — how much evidence sits behind the value. Rendered as ink density. */
  confidence: number
  sources: AxisSource[]
}

/** Structured signals harvested from Amap (高德) POI data. */
export interface AmapSignals {
  id: string
  rating?: number
  cost?: number
  openHours?: string
  fetchedAt: string
}

/**
 * Structured signals read from Dianping (大众点评) public shop pages served to
 * the Apple Maps integration channel. Counts arrive as display strings
 * (“4万+”) and are parsed at blend time.
 */
export interface DianpingSignals {
  shopId: string
  rating?: number
  /** 人均 in ¥. */
  avgPrice?: number
  reviewCountText?: string
  picCountStr?: string
  categoryName?: string
  regionName?: string
  fetchedAt: string
}

export interface Evidence {
  axes?: Partial<Record<keyof Axes, AxisEvidence>>
  amap?: AmapSignals
  dianping?: DianpingSignals
}

/**
 * What kind of thing a trait is about. Traits are the café-specific, evidenced
 * observations that replace generic tags: "east bar window, morning sun till
 * 10:30" rather than "outdoor".
 */
export type TraitKind =
  | 'space'
  | 'light'
  | 'view'
  | 'seating'
  | 'sound'
  | 'beans'
  | 'drinks'
  | 'food'
  | 'people'
  | 'time'
  | 'story'

export type TraitEvidence = 'photo' | 'web' | 'amap' | 'dianping' | 'osm' | 'editorial'

export interface Trait {
  kind: TraitKind
  /** English, one clause, specific. ≤ 70 characters. */
  text: string
  /** 中文，一句，具体。≤ 26 字。 */
  textZh: string
  evidence: TraitEvidence[]
  /** 0..1 — how sure the pipeline is. Below 0.5 is never shown as fact. */
  confidence: number
  /** Source URL when the trait was read from a public page. */
  source?: string
}

/** A structured nudge for one compass axis, with the reason in plain words. */
export interface AxisHint {
  value: number
  confidence: number
  because: string
  becauseZh: string
}

/**
 * Per-café detail generated by tools/enrich (photos, dishes, weekly hours,
 * evidenced traits). Absent = nothing beyond the editorial record.
 */
export interface CafeDetail {
  /** Amap photo URLs, up to 4. */
  photos: string[]
  /** Amap recommended items (Chinese), as listed. */
  dishes: string[]
  /** Weekly hours when known; day 0 = Sunday. */
  hours?: { day: number; open: number; close: number }[]
  /** 2–6 traits, most distinctive first. */
  traits: Trait[]
  /** One line that says why this room and not the next one. */
  headline?: { en: string; zh: string }
  axisHints?: Partial<Record<keyof Axes, AxisHint>>
}

